### ISSUE TITLE
WVDLogix-Autscaling.ps1 error when calling CreateOrUpdateAzAutoAccount.ps1

### ISSUE THREAD

**Issue by bderry71** [wvdlogix/WVDLOGIX-Scripts#1]
I'm getting this error when trying to deploy with WVDLogix-Autoscaling.ps1 from your repo.

```
C:\scripts\wvd\Autoscaling\CreateOrUpdateAzAutoAccount.ps1 : Cannot validate argument on parameter 'Name'. The
argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At C:\scripts\wvd\Autoscaling\WVDLogix-Autoscaling.ps1:58 char:1
+ .\CreateOrUpdateAzAutoAccount.ps1 @Params
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [CreateOrUpdateAzAutoAccount.ps1], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,CreateOrUpdateAzAutoAccount.ps1

C:\scripts\wvd\Autoscaling\New-RunAsAccount.ps1 : Cannot bind argument to parameter 'ResourceGroup' because it is an
empty string.
At C:\scripts\wvd\Autoscaling\WVDLogix-Autoscaling.ps1:64 char:39
+ .\New-RunAsAccount.ps1 -ResourceGroup $AutomationRGName -AutomationAc ...
+                                       ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-RunAsAccount.ps1], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,New-RunAsAccount.ps1

```

**Comment by pkoehlercloud** [comment]
Dear bderry71! Thanks for your request. 

I could see from your logs, that the value for the ResourceGroup has been empty, this is not allowed, as the script doesn´t know where to place the resources. Please fill out the value from within the PowerShell to make the script work. 

Btw. I´ve released a newer version that is not yet available on GitHub because of some trouble with the account at a time. 

Please try the latest version available here: https://wvdlogix.net/wvdlogix-autoscaling-tool

It comes with a GUI and better control over missing parameters! The next version is already planned by mid of October 2020.

Thanks a lot and feel free to reach out to me if something is missing.
